[package]
name = "gps-interface"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
serde = { version = "1.0.228", features = ["derive"] }
serialport = {version="4.8.1"}
tokio = { version = "1.48.0", features = ["full"] }
toml = "0.9.8"

